# Generated by Django 5.1.3 on 2026-03-20 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IRM3007', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradeprocess',
            name='course',
        ),
        migrations.RemoveField(
            model_name='gradeprocess',
            name='student',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='GradeProcess',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
