# Generated by Django 5.1.3 on 2026-03-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='course_code',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
