# Generated by Django 5.1.3 on 2026-03-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_assignment_course_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='instruction_file',
            field=models.FileField(blank=True, null=True, upload_to='instructions/'),
        ),
    ]
